# Generated by Django 5.2.7 on 2025-10-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='min_responses_for_anonymity',
            field=models.IntegerField(default=3, help_text='Minimum number of responses required to show results (for anonymity). Set to 1 for small teams.'),
        ),
    ]
