# Generated by Django 5.2.7 on 2025-10-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_min_responses_for_anonymity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_registration',
            field=models.BooleanField(default=False, help_text='Allow new users to register for this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_users_can_create_cycles',
            field=models.BooleanField(default=False, help_text='By default, new users can create cycles for others (not just themselves)'),
        ),
    ]
