# Generated by Django 5.2.7 on 2025-10-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_allow_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for subdomain (e.g., acme for acme.yourdomain.com). Leave blank to disable subdomain access.', max_length=100, null=True, unique=True),
        ),
    ]
