# Generated by Django 5.2.7 on 2025-10-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
    ]
