# Generated by Django 5.2.7 on 2025-10-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_encrypt_smtp_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeEmailFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short title for the fact (e.g., "The Power of 360 Feedback")', max_length=255)),
                ('content', models.TextField(help_text='The fact content. Can include HTML tags like <strong> for emphasis.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active facts will be shown in emails')),
                ('display_order', models.IntegerField(default=0, help_text='Optional ordering (lower numbers shown first when not randomizing)')),
            ],
            options={
                'verbose_name': 'Welcome Email Fact',
                'verbose_name_plural': 'Welcome Email Facts',
                'db_table': 'welcome_email_facts',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
