# Generated by Django 5.2.7 on 2025-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_welcomeemailfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_send_report_email',
            field=models.BooleanField(default=True, help_text='Automatically send email to reviewee when their report is generated'),
        ),
    ]
