"""
Factory definitions for review models
"""
import factory
from factory.django import DjangoModelFactory
import uuid
from .models import ReviewCycle, ReviewerToken, Response
from accounts.factories import RevieweeFactory
from questionnaires.factories import QuestionnaireFactory, QuestionFactory
from core.factories import UserFactory


class ReviewCycleFactory(DjangoModelFactory):
    """Factory for creating review cycles"""

    class Meta:
        model = ReviewCycle

    reviewee = factory.SubFactory(RevieweeFactory)
    questionnaire = factory.SubFactory(QuestionnaireFactory)
    created_by = factory.SubFactory(UserFactory)
    status = 'active'

    # Tokens are auto-generated by the model's save method


class ReviewerTokenFactory(DjangoModelFactory):
    """Factory for creating reviewer tokens"""

    class Meta:
        model = ReviewerToken

    cycle = factory.SubFactory(ReviewCycleFactory)
    token = factory.LazyFunction(uuid.uuid4)
    category = 'peer'
    reviewer_email = None
    invitation_sent_at = None
    claimed_at = None
    completed_at = None


class SelfReviewTokenFactory(ReviewerTokenFactory):
    """Factory for self-review tokens"""
    category = 'self'


class PeerReviewTokenFactory(ReviewerTokenFactory):
    """Factory for peer review tokens"""
    category = 'peer'


class ManagerReviewTokenFactory(ReviewerTokenFactory):
    """Factory for manager review tokens"""
    category = 'manager'


class DirectReportReviewTokenFactory(ReviewerTokenFactory):
    """Factory for direct report review tokens"""
    category = 'direct_report'


class ResponseFactory(DjangoModelFactory):
    """Factory for creating responses"""

    class Meta:
        model = Response

    cycle = factory.SubFactory(ReviewCycleFactory)
    question = factory.SubFactory(QuestionFactory)
    token = factory.SubFactory(ReviewerTokenFactory)
    category = factory.LazyAttribute(lambda obj: obj.token.category)
    answer_data = factory.LazyFunction(lambda: {'value': 3})


class RatingResponseFactory(ResponseFactory):
    """Factory for rating responses"""

    answer_data = factory.LazyFunction(lambda: {'value': 4})


class TextResponseFactory(ResponseFactory):
    """Factory for text responses"""

    answer_data = factory.Faker('sentence', nb_words=20)
