# Generated by Django 5.2.7 on 2025-11-04 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_add_auto_send_report_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the token (e.g., 'Slack Bot', 'Analytics Dashboard')",
                        max_length=255,
                    ),
                ),
                (
                    "token",
                    models.CharField(db_index=True, editable=False, max_length=64, unique=True),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Permissions as JSON: {"read:cycles": true, "write:cycles": true}',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Token expiration date/time (null = never expires)",
                        null=True,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "rate_limit",
                    models.IntegerField(
                        default=1000, help_text="Maximum requests per hour for this token"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "db_table": "api_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Descriptive name for this webhook", max_length=255),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL to receive webhook POST requests", max_length=500
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text='List of event types to subscribe to: ["cycle.created", "cycle.completed", ...]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "secret",
                    models.CharField(
                        editable=False,
                        help_text="Secret for HMAC signature verification",
                        max_length=64,
                    ),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("success_count", models.IntegerField(default=0, editable=False)),
                ("failure_count", models.IntegerField(default=0, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "db_table": "webhook_endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(help_text="Event data sent to webhook")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "response_body",
                    models.TextField(
                        blank=True, help_text="Response body (truncated to 1000 chars)"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.IntegerField(default=0)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="api.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "-created_at"], name="webhook_del_endpoin_551ae2_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"], name="webhook_del_event_t_bd5437_idx"
                    ),
                ],
            },
        ),
    ]
