# Generated by Django 5.2.7 on 2025-11-04 22:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='delivery_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for this delivery (non-enumerable)'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
