# Generated by Django 5.2.7 on 2025-11-02 20:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_add_auto_send_report_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(help_text='Rating from 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_title', models.CharField(help_text='Short title/headline for the review', max_length=200)),
                ('review_text', models.TextField(help_text='Full review text from the customer')),
                ('reviewer_name', models.CharField(help_text='Name of the person giving the review', max_length=100)),
                ('reviewer_title', models.CharField(blank=True, help_text='Job title of the reviewer (e.g., "HR Manager")', max_length=150)),
                ('reviewer_company', models.CharField(blank=True, help_text='Company/organization the reviewer works for', max_length=100)),
                ('reviewer_email', models.EmailField(help_text='Email address of the reviewer (not shown publicly)', max_length=254)),
                ('verified_customer', models.BooleanField(default=False, help_text='Verified as actual customer/subscriber')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Review approval status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Active reviews can be displayed publicly')),
                ('featured', models.BooleanField(default=False, help_text='Featured reviews are highlighted on landing pages')),
                ('published_date', models.DateField(blank=True, help_text='Date the review was published (shown in JSON-LD)', null=True)),
                ('source', models.CharField(blank=True, help_text='Where the review came from (e.g., "Email Survey", "G2", "Direct")', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this review (not shown publicly)')),
                ('organization', models.ForeignKey(help_text='Organization this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='core.organization')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'db_table': 'product_reviews',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
