# Generated by Django 5.2.7 on 2025-10-25 21:26

from django.db import migrations


def create_profiles_for_existing_users(apps, schema_editor):
    """Create UserProfile for existing users who don't have one"""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    Organization = apps.get_model('core', 'Organization')

    # Get first organization (fallback for existing users)
    org = Organization.objects.first()

    if not org:
        # No organization yet, skip
        return

    # Get all users without profiles
    users_without_profiles = User.objects.filter(profile__isnull=True)

    for user in users_without_profiles:
        # Create profile with permissions based on staff status
        UserProfile.objects.create(
            user=user,
            organization=org,
            can_create_cycles_for_others=user.is_staff or user.is_superuser
        )


def reverse_func(apps, schema_editor):
    """Reverse migration - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('core', '0003_organization_allow_registration_and_more'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_users, reverse_func),
    ]
