# Generated by Django 5.2.7 on 2025-10-26 13:22

from django.db import migrations


def assign_permissions_to_existing_users(apps, schema_editor):
    """
    Assign Django permissions to existing users based on their is_staff flag.

    - Users with is_staff=True get Organization Admin permissions
    - Users with is_staff=False get Organization Member permissions
    """
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    # Get UserProfile content type
    try:
        content_type = ContentType.objects.get(app_label='accounts', model='userprofile')
    except ContentType.DoesNotExist:
        print("ContentType for UserProfile not found, skipping permission assignment")
        return

    # Create permissions if they don't exist
    invite_permission, _ = Permission.objects.get_or_create(
        codename='can_invite_members',
        content_type=content_type,
        defaults={'name': 'Can invite team members'}
    )

    manage_org_permission, _ = Permission.objects.get_or_create(
        codename='can_manage_organization',
        content_type=content_type,
        defaults={'name': 'Can manage organization settings'}
    )

    delete_org_permission, _ = Permission.objects.get_or_create(
        codename='can_delete_organization',
        content_type=content_type,
        defaults={'name': 'Can delete organization'}
    )

    view_all_reports_permission, _ = Permission.objects.get_or_create(
        codename='can_view_all_reports',
        content_type=content_type,
        defaults={'name': 'Can view all organization reports'}
    )

    # Create groups
    admin_group, _ = Group.objects.get_or_create(name='Organization Admin')
    admin_group.permissions.set([
        invite_permission,
        manage_org_permission,
        delete_org_permission,
        view_all_reports_permission,
    ])

    member_group, _ = Group.objects.get_or_create(name='Organization Member')
    # Members have no special permissions by default

    # Assign users to groups based on is_staff flag
    admin_count = 0
    member_count = 0

    for user in User.objects.all():
        # Skip superusers (they already have all permissions)
        if user.is_superuser:
            continue

        if user.is_staff:
            # Assign as organization admin
            user.groups.add(admin_group)
            admin_count += 1
        else:
            # Assign as organization member
            user.groups.add(member_group)
            member_count += 1

    print(f"Assigned permissions: {admin_count} admins, {member_count} members")


def reverse_permissions(apps, schema_editor):
    """
    Remove all users from organization groups.
    """
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')

    try:
        admin_group = Group.objects.get(name='Organization Admin')
        member_group = Group.objects.get(name='Organization Member')

        for user in User.objects.all():
            user.groups.remove(admin_group, member_group)
    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizationinvitation'),
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={
                'ordering': ['user__username'],
                'permissions': [
                    ('can_invite_members', 'Can invite team members'),
                    ('can_manage_organization', 'Can manage organization settings'),
                    ('can_delete_organization', 'Can delete organization'),
                    ('can_view_all_reports', 'Can view all organization reports'),
                ],
            },
        ),
        migrations.RunPython(assign_permissions_to_existing_users, reverse_permissions),
    ]
