# Generated by Django 5.2.7 on 2025-10-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assign_organization_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_welcome',
            field=models.BooleanField(default=False, help_text='Whether user has seen the welcome modal'),
        ),
    ]
