# Generated by Django 5.2.7 on 2025-10-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='access_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Secure token for reviewee access to their report', null=True, unique=True),
        ),
    ]
