# Generated by Django 5.2.7 on 2025-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='access_count',
            field=models.IntegerField(default=0, help_text='Number of times report has been accessed'),
        ),
        migrations.AddField(
            model_name='report',
            name='access_token_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration date for access token', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time report was accessed', null=True),
        ),
    ]
