# Generated by Django 5.2.7 on 2025-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating Scale'), ('likert', 'Likert Scale'), ('text', 'Free Text'), ('multiple_choice', 'Multiple Choice')], max_length=20),
        ),
    ]
