# Generated by Django 5.2.7 on 2025-10-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_min_responses_for_anonymity'),
        ('questionnaires', '0002_add_likert_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='core.organization'),
        ),
    ]
