# Generated by Django 5.2.7 on 2025-10-28 20:00

from django.db import migrations


def create_agency_questionnaire(apps, schema_editor):
    """Create the Agency & Initiative Assessment questionnaire"""
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')
    QuestionSection = apps.get_model('questionnaires', 'QuestionSection')
    Question = apps.get_model('questionnaires', 'Question')
    Organization = apps.get_model('core', 'Organization')

    # Create questionnaire (as a template with organization=None and is_default=True)
    # This will be cloned to all organizations via the post_save signal
    questionnaire = Questionnaire.objects.create(
        name="Agency & Initiative Assessment",
        description="Quick assessment focused on problem-solving maturity, initiative, and ownership. Based on the 5-level agency framework: from identifying problems to independently implementing solutions.",
        organization=None,  # Template questionnaire
        is_default=True,  # Mark as default template so it gets cloned to new orgs
        is_active=True,
    )

    # Section 1: Problem Identification
    section1 = QuestionSection.objects.create(
        questionnaire=questionnaire,
        title="Problem Identification",
        description="How effectively does this person spot and communicate issues?",
        order=1
    )

    Question.objects.create(
        section=section1,
        question_text="How effectively does this person identify problems before they escalate?",
        question_type="rating",
        config={
            "min": 1,
            "max": 5,
            "labels": {
                "1": "Misses problems",
                "2": "Spots major issues",
                "3": "Identifies most problems",
                "4": "Proactively catches issues",
                "5": "Exceptional foresight"
            },
            "chart_weight": 1.0
        },
        required=True,
        order=1
    )

    Question.objects.create(
        section=section1,
        question_text="When this person raises a problem, they typically:",
        question_type="multiple_choice",
        config={
            "choices": [
                "Just mentions the problem exists",
                "Describes the problem with context",
                "Explains problem and explores causes",
                "Presents thorough root cause analysis"
            ]
        },
        required=True,
        order=2
    )

    # Section 2: Solution Thinking
    section2 = QuestionSection.objects.create(
        questionnaire=questionnaire,
        title="Solution Thinking",
        description="Does this person bring solutions, not just problems?",
        order=2
    )

    Question.objects.create(
        section=section2,
        question_text="This person proactively suggests solutions when raising issues",
        question_type="likert",
        config={
            "scale": [
                "Strongly Disagree",
                "Disagree",
                "Neutral",
                "Agree",
                "Strongly Agree"
            ]
        },
        required=True,
        order=1
    )

    Question.objects.create(
        section=section2,
        question_text="Quality of solutions this person proposes",
        question_type="rating",
        config={
            "min": 1,
            "max": 5,
            "labels": {
                "1": "Impractical",
                "2": "Occasionally viable",
                "3": "Generally sound",
                "4": "Well-thought-out",
                "5": "Highly practical"
            },
            "chart_weight": 1.5
        },
        required=True,
        order=2
    )

    # Section 3: Decision Making
    section3 = QuestionSection.objects.create(
        questionnaire=questionnaire,
        title="Decision Making",
        description="How well does this person make and communicate recommendations?",
        order=3
    )

    Question.objects.create(
        section=section3,
        question_text="This person clearly recommends their preferred solution with reasoning",
        question_type="likert",
        config={
            "scale": [
                "Strongly Disagree",
                "Disagree",
                "Neutral",
                "Agree",
                "Strongly Agree"
            ]
        },
        required=True,
        order=1
    )

    Question.objects.create(
        section=section3,
        question_text="When presenting options, this person:",
        question_type="multiple_choice",
        config={
            "choices": [
                "Lists options without preference",
                "Leans toward one informally",
                "Recommends with basic reasoning",
                "Provides clear recommendation with thorough analysis"
            ]
        },
        required=True,
        order=2
    )

    # Section 4: Ownership & Execution
    section4 = QuestionSection.objects.create(
        questionnaire=questionnaire,
        title="Ownership & Execution",
        description="Does this person take initiative and follow through?",
        order=4
    )

    Question.objects.create(
        section=section4,
        question_text="How often does this person independently implement solutions they identify?",
        question_type="rating",
        config={
            "min": 1,
            "max": 5,
            "labels": {
                "1": "Never - waits for direction",
                "2": "Rarely - needs prompting",
                "3": "Sometimes - with approval",
                "4": "Often - takes initiative",
                "5": "Always - highly autonomous"
            },
            "chart_weight": 2.0
        },
        required=True,
        order=1
    )

    Question.objects.create(
        section=section4,
        question_text="This person keeps stakeholders appropriately informed when taking initiative",
        question_type="likert",
        config={
            "scale": [
                "Strongly Disagree",
                "Disagree",
                "Neutral",
                "Agree",
                "Strongly Agree"
            ]
        },
        required=True,
        order=2
    )

    Question.objects.create(
        section=section4,
        question_text="This person's typical approach to problems is:",
        question_type="multiple_choice",
        config={
            "choices": [
                "Waits for direction before acting",
                "Takes action after getting approval",
                "Often acts independently then reports",
                "Consistently acts independently with proper communication"
            ]
        },
        required=True,
        order=3
    )

    # Section 5: Examples & Development
    section5 = QuestionSection.objects.create(
        questionnaire=questionnaire,
        title="Examples & Development",
        description="Specific examples and growth opportunities",
        order=5
    )

    Question.objects.create(
        section=section5,
        question_text="Provide an example of this person demonstrating high agency (identifying a problem and driving it to resolution)",
        question_type="text",
        config={},
        required=False,
        order=1
    )

    Question.objects.create(
        section=section5,
        question_text="What could help this person operate with more agency and initiative?",
        question_type="text",
        config={},
        required=False,
        order=2
    )

    # Clone this template questionnaire to all existing organizations
    # (New orgs will get it automatically via the post_save signal)
    for org in Organization.objects.all():
        clone_questionnaire_for_org(questionnaire, org, Questionnaire, QuestionSection, Question)


def clone_questionnaire_for_org(template, organization, Questionnaire, QuestionSection, Question):
    """
    Clone a template questionnaire for a specific organization.
    This is a migration-safe version that doesn't rely on signals.
    """
    # Clone the questionnaire
    original_pk = template.pk
    template.pk = None
    template.id = None
    template.organization = organization
    template.is_default = False  # Only templates should be marked as default
    template.save()

    cloned_questionnaire = template

    # Clone all sections
    sections = QuestionSection.objects.filter(questionnaire_id=original_pk).order_by('order')
    section_mapping = {}

    for section in sections:
        original_section_pk = section.pk
        section.pk = None
        section.id = None
        section.questionnaire = cloned_questionnaire
        section.save()
        section_mapping[original_section_pk] = section

    # Clone all questions
    for original_section_pk, cloned_section in section_mapping.items():
        questions = Question.objects.filter(section_id=original_section_pk).order_by('order')
        for question in questions:
            question.pk = None
            question.id = None
            question.section = cloned_section
            question.save()

    return cloned_questionnaire


def reverse_agency_questionnaire(apps, schema_editor):
    """
    Remove the Agency & Initiative Assessment questionnaire.

    This removes:
    - The template questionnaire (organization=None)
    - All organization-specific clones
    - All related sections and questions (cascade delete)
    """
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')

    # Delete all questionnaires with this name (template + all org clones)
    # Related sections and questions will cascade delete
    deleted_count, _ = Questionnaire.objects.filter(
        name="Agency & Initiative Assessment"
    ).delete()

    # Log deletion for transparency during rollback
    if deleted_count > 0:
        print(f"Deleted {deleted_count} 'Agency & Initiative Assessment' questionnaire(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_questionnaire_organization'),
    ]

    operations = [
        migrations.RunPython(create_agency_questionnaire, reverse_agency_questionnaire),
    ]
