# Generated by Django 5.2.7 on 2025-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_rename_multiple_choice_to_single_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating Scale'), ('likert', 'Likert Scale'), ('text', 'Free Text'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('scale', 'Numeric Scale')], max_length=20),
        ),
    ]
