# Generated by Django on 2025-10-31

from django.db import migrations


def create_manager_questionnaire(apps, schema_editor):
    """
    Create the Manager 360 Review questionnaire.
    
    This migration supports both programmatic creation and fixture loading:
    - If the template already exists (loaded from fixture), it skips creation
    - Otherwise, it creates the questionnaire programmatically
    - In both cases, it clones to all existing organizations
    """
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')
    QuestionSection = apps.get_model('questionnaires', 'QuestionSection')
    Question = apps.get_model('questionnaires', 'Question')
    Organization = apps.get_model('core', 'Organization')

    # Check if the template already exists (e.g., loaded from fixture)
    existing_template = Questionnaire.objects.filter(
        name="Manager 360 Review",
        organization__isnull=True
    ).first()

    if existing_template:
        print("✓ Manager 360 Review template already exists (loaded from fixture)")
        questionnaire = existing_template
    else:
        # Create questionnaire programmatically
        questionnaire = Questionnaire.objects.create(
            name="Manager 360 Review",
            description="360-degree feedback questionnaire for managers and team leads, assessing leadership effectiveness, direction-setting, team impact, and people development.",
            organization=None,
            is_default=True,
            is_active=True,
        )

        # Section 1: Leadership
        section1 = QuestionSection.objects.create(
            questionnaire=questionnaire,
            title="Leadership",
            description="Visibility, trust, and communication",
            order=1
        )

        Question.objects.create(
            section=section1,
            question_text="My manager is visible and engaged with the team",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Rarely present or engaged",
                    "2": "Occasionally visible",
                    "3": "Regularly engaged",
                    "4": "Consistently visible and accessible",
                    "5": "Exceptionally present and engaged"
                }
            },
            required=True,
            order=1
        )

        Question.objects.create(
            section=section1,
            question_text="I trust my manager's intentions and decisions",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Low trust",
                    "2": "Some concerns",
                    "3": "Generally trustworthy",
                    "4": "High trust",
                    "5": "Complete trust"
                }
            },
            required=True,
            order=2
        )

        Question.objects.create(
            section=section1,
            question_text="My manager communicates clearly about decisions and their reasoning",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Rarely explains decisions",
                    "2": "Occasionally provides context",
                    "3": "Usually communicates reasoning",
                    "4": "Consistently clear communication",
                    "5": "Exemplary transparency and clarity"
                }
            },
            required=True,
            order=3
        )

        # Section 2: Direction
        section2 = QuestionSection.objects.create(
            questionnaire=questionnaire,
            title="Direction",
            description="Goal setting, clarity, and problem-solving",
            order=2
        )

        Question.objects.create(
            section=section2,
            question_text="Goals and priorities are clearly defined",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Goals are unclear or missing",
                    "2": "Some clarity, but gaps remain",
                    "3": "Goals are mostly clear",
                    "4": "Clear and well-defined goals",
                    "5": "Crystal clear priorities and objectives"
                }
            },
            required=True,
            order=1
        )

        Question.objects.create(
            section=section2,
            question_text="My manager provides clear direction and gives me autonomy to execute",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Too hands-off or micromanaging",
                    "2": "Direction needs improvement",
                    "3": "Good balance of guidance and autonomy",
                    "4": "Excellent direction with appropriate freedom",
                    "5": "Perfect balance of clarity and empowerment"
                }
            },
            required=True,
            order=2
        )

        Question.objects.create(
            section=section2,
            question_text="Problems or obstacles are discussed and addressed in time",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Issues are ignored or delayed",
                    "2": "Slow to address problems",
                    "3": "Problems are handled reasonably",
                    "4": "Proactive problem-solving",
                    "5": "Exceptional at anticipating and resolving issues"
                }
            },
            required=True,
            order=3
        )

        # Section 3: Expertise & Judgment
        section3 = QuestionSection.objects.create(
            questionnaire=questionnaire,
            title="Expertise & Judgment",
            description="Domain knowledge and decision-making quality",
            order=3
        )

        Question.objects.create(
            section=section3,
            question_text="My manager understands the content of our work well enough to guide effectively",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Limited understanding",
                    "2": "Basic awareness",
                    "3": "Sufficient knowledge to guide",
                    "4": "Strong understanding of our work",
                    "5": "Deep expertise and insight"
                }
            },
            required=True,
            order=1
        )

        Question.objects.create(
            section=section3,
            question_text="My manager makes informed decisions about our work",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Decisions often miss the mark",
                    "2": "Sometimes uninformed",
                    "3": "Generally sound decisions",
                    "4": "Consistently well-informed decisions",
                    "5": "Exceptionally wise judgment"
                }
            },
            required=True,
            order=2
        )

        # Section 4: Impact
        section4 = QuestionSection.objects.create(
            questionnaire=questionnaire,
            title="Impact",
            description="Contribution to team performance and results",
            order=4
        )

        Question.objects.create(
            section=section4,
            question_text="My manager's way of leading contributes visibly to team performance",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Negative impact on performance",
                    "2": "Limited contribution",
                    "3": "Positive impact on team",
                    "4": "Significantly improves performance",
                    "5": "Transformative leadership impact"
                }
            },
            required=True,
            order=1
        )

        Question.objects.create(
            section=section4,
            question_text="My manager encourages results-oriented work",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Focus on process over results",
                    "2": "Some results focus",
                    "3": "Balanced approach",
                    "4": "Strong results orientation",
                    "5": "Exceptional focus on meaningful outcomes"
                }
            },
            required=True,
            order=2
        )

        # Section 5: Feedback & Recognition
        section5 = QuestionSection.objects.create(
            questionnaire=questionnaire,
            title="Feedback & Recognition",
            description="Quality of feedback and acknowledgment of contributions",
            order=5
        )

        Question.objects.create(
            section=section5,
            question_text="I receive regular, useful feedback from my manager",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Rarely receive feedback",
                    "2": "Infrequent or unhelpful feedback",
                    "3": "Regular, adequate feedback",
                    "4": "Frequent, actionable feedback",
                    "5": "Exceptional feedback quality and frequency"
                }
            },
            required=True,
            order=1
        )

        Question.objects.create(
            section=section5,
            question_text="My manager recognizes good work when it happens",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Recognition is absent",
                    "2": "Rarely acknowledges contributions",
                    "3": "Recognizes good work adequately",
                    "4": "Consistently acknowledges achievements",
                    "5": "Outstanding at celebrating contributions"
                }
            },
            required=True,
            order=2
        )

        # Section 6: Development
        section6 = QuestionSection.objects.create(
            questionnaire=questionnaire,
            title="Development",
            description="Support for growth and skill development",
            order=6
        )

        Question.objects.create(
            section=section6,
            question_text="My manager encourages personal and professional growth",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "No focus on development",
                    "2": "Limited encouragement",
                    "3": "Supports growth opportunities",
                    "4": "Actively promotes development",
                    "5": "Champion of personal and professional growth"
                }
            },
            required=True,
            order=1
        )

        Question.objects.create(
            section=section6,
            question_text="My manager recognizes and names individual strengths",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "Doesn't identify strengths",
                    "2": "Occasionally notes strengths",
                    "3": "Recognizes key strengths",
                    "4": "Consistently highlights strengths",
                    "5": "Exceptional at identifying and leveraging strengths"
                }
            },
            required=True,
            order=2
        )

        Question.objects.create(
            section=section6,
            question_text="My manager supports the development of new skills",
            question_type="rating",
            config={
                "min": 1,
                "max": 5,
                "labels": {
                    "1": "No support for skill development",
                    "2": "Limited support",
                    "3": "Provides opportunities to learn",
                    "4": "Actively supports skill building",
                    "5": "Creates excellent learning opportunities"
                }
            },
            required=True,
            order=3
        )

        # Section 7: Overall Feedback
        section7 = QuestionSection.objects.create(
            questionnaire=questionnaire,
            title="Overall Feedback",
            description="Open-ended feedback and suggestions",
            order=7
        )

        Question.objects.create(
            section=section7,
            question_text="What should this person keep doing?",
            question_type="text",
            config={},
            required=False,
            order=1
        )

        Question.objects.create(
            section=section7,
            question_text="What should this person do differently?",
            question_type="text",
            config={},
            required=False,
            order=2
        )

        print("✓ Created Manager 360 Review template questionnaire")

    # Clone to all existing organizations (whether from fixture or programmatic creation)
    cloned_count = 0
    for org in Organization.objects.all():
        # Check if org already has this questionnaire
        has_questionnaire = Questionnaire.objects.filter(
            organization=org,
            name="Manager 360 Review"
        ).exists()

        if has_questionnaire:
            continue

        clone_questionnaire_for_org(questionnaire, org, Questionnaire, QuestionSection, Question)
        cloned_count += 1

    if cloned_count > 0:
        print(f"✓ Cloned Manager 360 Review to {cloned_count} existing organization(s)")


def clone_questionnaire_for_org(template, organization, Questionnaire, QuestionSection, Question):
    """
    Clone a template questionnaire for a specific organization.
    This is a migration-safe version that doesn't rely on signals.
    """
    original_pk = template.pk
    template.pk = None
    template.id = None
    template.organization = organization
    template.is_default = False
    template.save()

    cloned_questionnaire = template

    sections = QuestionSection.objects.filter(questionnaire_id=original_pk).order_by('order')
    section_mapping = {}

    for section in sections:
        original_section_pk = section.pk
        section.pk = None
        section.id = None
        section.questionnaire = cloned_questionnaire
        section.save()
        section_mapping[original_section_pk] = section

    for original_section_pk, cloned_section in section_mapping.items():
        questions = Question.objects.filter(section_id=original_section_pk).order_by('order')
        for question in questions:
            question.pk = None
            question.id = None
            question.section = cloned_section
            question.save()

    return cloned_questionnaire


def reverse_manager_questionnaire(apps, schema_editor):
    """Remove the Manager 360 Review questionnaire"""
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')

    deleted_count, _ = Questionnaire.objects.filter(
        name="Manager 360 Review"
    ).delete()

    if deleted_count > 0:
        print(f"Deleted {deleted_count} 'Manager 360 Review' questionnaire(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_add_scale_question_type'),
    ]

    operations = [
        migrations.RunPython(create_manager_questionnaire, reverse_manager_questionnaire),
    ]
