# Generated by Django on 2025-11-07

from django.db import migrations
import json
import uuid as uuid_module
from pathlib import Path


def load_simple_questionnaire(apps, schema_editor):
    """
    Load 360 Degree Feedback questionnaire from fixture.
    Uses fixture data but ignores PKs to avoid conflicts.
    """
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')
    QuestionSection = apps.get_model('questionnaires', 'QuestionSection')
    Question = apps.get_model('questionnaires', 'Question')
    Organization = apps.get_model('core', 'Organization')

    # Check if template already exists
    existing = Questionnaire.objects.filter(
        name="360 Degree Feedback",
        organization__isnull=True
    ).first()

    if existing:
        print("✓ 360 Degree Feedback template already exists")
        questionnaire = existing
    else:
        # Load fixture data
        fixture_path = Path(__file__).parent.parent / 'fixtures' / 'simple_questionnaire.json'
        with open(fixture_path, 'r') as f:
            fixture_data = json.load(f)

        # Find questionnaire data
        q_data = next(item for item in fixture_data if item['model'] == 'questionnaires.questionnaire')

        # Create questionnaire (ignore PK from fixture)
        questionnaire = Questionnaire.objects.create(
            name=q_data['fields']['name'],
            description=q_data['fields']['description'],
            is_default=True,
            is_active=True,
            organization=None
        )

        # Get all sections from fixture
        sections_data = [item for item in fixture_data if item['model'] == 'questionnaires.questionsection']
        sections_data.sort(key=lambda x: x['fields']['order'])

        # Map old section PKs to new section objects
        section_pk_map = {}

        for section_data in sections_data:
            old_pk = section_data['pk']
            section = QuestionSection.objects.create(
                questionnaire=questionnaire,
                title=section_data['fields']['title'],
                description=section_data['fields']['description'],
                order=section_data['fields']['order']
            )
            section_pk_map[old_pk] = section

        # Get all questions from fixture
        questions_data = [item for item in fixture_data if item['model'] == 'questionnaires.question']

        # Group questions by section
        for question_data in questions_data:
            old_section_pk = question_data['fields']['section']
            if old_section_pk in section_pk_map:
                Question.objects.create(
                    section=section_pk_map[old_section_pk],
                    question_text=question_data['fields']['question_text'],
                    question_type=question_data['fields']['question_type'],
                    config=question_data['fields']['config'],
                    required=question_data['fields']['required'],
                    order=question_data['fields']['order']
                )

        print("✓ Created 360 Degree Feedback template")

    # Clone to all existing organizations
    cloned_count = 0
    for org in Organization.objects.all():
        # Check if org already has this questionnaire
        has_questionnaire = Questionnaire.objects.filter(
            organization=org,
            name="360 Degree Feedback"
        ).exists()

        if has_questionnaire:
            continue

        clone_questionnaire_for_org(questionnaire, org, Questionnaire, QuestionSection, Question)
        cloned_count += 1

    if cloned_count > 0:
        print(f"✓ Cloned 360 Degree Feedback to {cloned_count} organization(s)")


def clone_questionnaire_for_org(template, organization, Questionnaire, QuestionSection, Question):
    """
    Clone a template questionnaire for a specific organization.
    This is a migration-safe version that doesn't rely on signals.
    """
    original_pk = template.pk
    template.pk = None
    template.id = None
    template.uuid = uuid_module.uuid4()  # Generate a new UUID for the clone
    template.organization = organization
    template.is_default = False
    template.save()

    cloned_questionnaire = template

    sections = QuestionSection.objects.filter(questionnaire_id=original_pk).order_by('order')
    section_mapping = {}

    for section in sections:
        original_section_pk = section.pk
        section.pk = None
        section.id = None
        section.questionnaire = cloned_questionnaire
        section.save()
        section_mapping[original_section_pk] = section

    for original_section_pk, cloned_section in section_mapping.items():
        questions = Question.objects.filter(section_id=original_section_pk).order_by('order')
        for question in questions:
            question.pk = None
            question.id = None
            question.section = cloned_section
            question.save()

    return cloned_questionnaire


def reverse_simple_questionnaire(apps, schema_editor):
    """Remove 360 Degree Feedback questionnaire"""
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')

    deleted_count, _ = Questionnaire.objects.filter(
        name="360 Degree Feedback"
    ).delete()

    if deleted_count > 0:
        print(f"Deleted {deleted_count} '360 Degree Feedback' questionnaire(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_add_professional_skills_questionnaire'),
        ('core', '0001_initial'),  # Need Organization model
    ]

    operations = [
        migrations.RunPython(
            load_simple_questionnaire,
            reverse_simple_questionnaire
        ),
    ]
