# Generated by Django on 2025-01-08

from django.db import migrations
import json


def update_questionnaires_with_dreyfus_metadata(apps, schema_editor):
    """
    Update existing Software Engineering and Professional Skills questionnaires
    with Dreyfus metadata and fix Q7 wording.
    """
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')
    Question = apps.get_model('questionnaires', 'Question')

    # Define question mappings for both questionnaires
    # Maps question text patterns to their dreyfus_mapping config

    # New format supports dual dimensions: {"skill": 1.5, "agency": 0.5}
    # Old format still supported for backward compatibility: {"dimension": "skill", "weight": 1.0}

    software_engineering_mappings = {
        # Q1 - Understanding customer problems
        "Understanding customer problems": {
            "skill": 1.0
        },
        # Q3 - Code quality
        "Rate their ability to translate ideas into clear, readable code": {
            "skill": 1.5
        },
        # Q4 - Team collaboration
        "How well does this person work with the team to solve complex problems?": {
            "agency": 0.5
        },
        # Q7 - Technical problem solving (UPDATED - removes "Dreyfus Model" reference)
        "What is their current skill level in their primary technology domain? (Dreyfus Model)": {
            "new_text": "How do they approach solving technical problems in their domain?",
            "new_labels": {
                "1": "Needs step-by-step instructions and close guidance",
                "2": "Can handle familiar problems with some guidance",
                "3": "Independently solves standard problems and plans work",
                "4": "Sees patterns quickly and handles complex situations",
                "5": "Intuitively finds solutions and creates novel approaches"
            },
            "dreyfus_mapping": {
                "skill": 1.5
            }
        },
        # Q8 - Stack familiarity
        "Rate their familiarity with the full technology stack": {
            "skill": 1.0
        },
        # Q9 - Tech trend awareness
        "How well do they identify emerging technologies and industry trends?": {
            "skill": 0.5,
            "agency": 0.5
        },
        # Q11 - Enthusiasm
        "How would you describe their enthusiasm for the work?": {
            "agency": 0.5
        },
        # Q12 - Initiative (PRIMARY agency indicator)
        "Do they demonstrate initiative in solving problems or improving processes?": {
            "agency": 1.5
        },
        # Q14 - Best practices
        "Rate their application of sound software development principles": {
            "skill": 1.0
        },
        # Q15 - Refactoring
        "How frequently do they refactor and improve existing code?": {
            "skill": 0.5,
            "agency": 1.0
        },
        # Q18 - Pragmatism
        "How well do they balance technical excellence with practical business goals?": {
            "skill": 1.0
        },
        # Q21 - Listening
        "How effectively do they listen and accept that others might have better ideas?": {
            "agency": 0.5
        },
        # Q22 - Mentoring
        "Do they share knowledge and mentor less experienced team members?": {
            "skill": 0.5,
            "agency": 0.5
        },
        # Q23 - Explanation clarity
        "How clearly can they explain technical decisions and system architecture?": {
            "skill": 1.0
        },
        # Q25 - Learning speed
        "How quickly do they learn and adopt new technologies?": {
            "skill": 0.5
        },
        # Q26 - Curiosity
        "Do they show curiosity for new languages, frameworks, or specifications?": {
            "agency": 1.0
        },
        # Q27 - Adaptability
        "How well do they adapt to changing requirements or circumstances?": {
            "skill": 0.5,
            "agency": 0.5
        },
        # Q29 - Business context
        "How well do they understand the broader product and business context?": {
            "skill": 1.0
        },
        # Q30 - Foresight
        "Do they demonstrate foresight for problems not yet encountered?": {
            "skill": 1.0
        },
        # Q31 - Team vision
        "How well do they contribute to and align with the shared team vision?": {
            "agency": 1.0
        }
    }

    professional_skills_mappings = {
        # Q1001 - Problem solving (PRIMARY skill indicator)
        "How effectively does this person analyze and solve problems?": {
            "skill": 1.5
        },
        # Q1002 - Decision making
        "How well does this person make decisions under pressure or with incomplete information?": {
            "skill": 1.0
        },
        # Q1004 - Communication
        "How clearly and effectively does this person communicate?": {
            "skill": 0.5
        },
        # Q1005 - Collaboration
        "How well does this person collaborate and work with others?": {
            "agency": 0.5
        },
        # Q1008 - Initiative (PRIMARY agency indicator)
        "How proactively does this person identify and address opportunities or challenges?": {
            "agency": 1.5
        },
        # Q1009 - Ownership
        "This person consistently takes ownership and follows through on commitments": {
            "agency": 1.0
        },
        # Q1011 - Learning speed
        "How quickly does this person learn new skills and concepts?": {
            "skill": 0.5
        },
        # Q1012 - Adaptability
        "How well does this person adapt to change and handle ambiguity?": {
            "skill": 0.5,
            "agency": 0.5
        },
        # Q1014 - Work quality
        "What is the quality of work this person delivers?": {
            "skill": 1.0
        },
        # Q1015 - Pragmatism
        "How well does this person balance quality with practical deadlines and constraints?": {
            "skill": 1.0
        },
        # Q1017 - Influence
        "How effectively does this person influence and guide others?": {
            "agency": 1.0
        },
        # Q1018 - Developing others
        "How well does this person develop and support the growth of others?": {
            "skill": 0.5,
            "agency": 0.5
        },
        # Q1019 - Strategic thinking
        "How well does this person understand and contribute to broader organizational goals?": {
            "skill": 1.0
        },
        # Q1022 - Self-awareness
        "How well does this person handle feedback and demonstrate self-awareness?": {
            "agency": 0.5
        }
    }

    # Update Software Engineering questionnaires
    se_questionnaires = Questionnaire.objects.filter(
        name="Software Engineering 360 Review"
    )

    se_updated = 0
    for questionnaire in se_questionnaires:
        for question in Question.objects.filter(section__questionnaire=questionnaire):
            # Check if question text matches any mapping (substring match for flexibility)
            for pattern, mapping in software_engineering_mappings.items():
                if pattern in question.question_text:
                    if question.config is None:
                        question.config = {}

                    # Special handling for Q7 - update text and labels
                    if "Dreyfus Model" in pattern:
                        question.question_text = mapping["new_text"]
                        question.config["labels"] = mapping["new_labels"]
                        question.config["dreyfus_mapping"] = mapping["dreyfus_mapping"]
                    else:
                        # Regular update - add metadata only
                        question.config["dreyfus_mapping"] = mapping

                    se_updated += 1
                    question.save()
                    break

    if se_updated > 0:
        print(f"✓ Updated {se_updated} questions in Software Engineering questionnaires with Dreyfus metadata")

    # Update Professional Skills questionnaires
    ps_questionnaires = Questionnaire.objects.filter(
        name="Professional Skills 360 Review"
    )

    ps_updated = 0
    for questionnaire in ps_questionnaires:
        for question in Question.objects.filter(section__questionnaire=questionnaire):
            # Check if question text matches any mapping
            for pattern, mapping in professional_skills_mappings.items():
                if pattern in question.question_text:
                    if question.config is None:
                        question.config = {}
                    question.config["dreyfus_mapping"] = mapping
                    ps_updated += 1
                    question.save()
                    break

    if ps_updated > 0:
        print(f"✓ Updated {ps_updated} questions in Professional Skills questionnaires with Dreyfus metadata")

    # Update questionnaire descriptions to mention Dreyfus assessment
    se_count = se_questionnaires.update(
        description="Comprehensive 360-degree feedback questionnaire for software engineers and technical roles, covering technical competencies, collaboration, and professional development with Dreyfus skill level assessment."
    )

    ps_count = ps_questionnaires.update(
        description="Universal 360-degree feedback questionnaire for all professional roles. Assesses core competencies including communication, problem-solving, collaboration, and leadership based on the Dreyfus model of skill acquisition."
    )

    if se_count > 0:
        print(f"✓ Updated {se_count} Software Engineering questionnaire descriptions")
    if ps_count > 0:
        print(f"✓ Updated {ps_count} Professional Skills questionnaire descriptions")


def reverse_dreyfus_metadata(apps, schema_editor):
    """
    Remove Dreyfus metadata from questionnaires and restore Q7.
    """
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')
    Question = apps.get_model('questionnaires', 'Question')

    # Revert Software Engineering questionnaires
    se_questionnaires = Questionnaire.objects.filter(
        name="Software Engineering 360 Review"
    )

    reverted = 0
    for questionnaire in se_questionnaires:
        for question in Question.objects.filter(section__questionnaire=questionnaire):
            # Remove dreyfus_mapping from config
            if question.config and "dreyfus_mapping" in question.config:
                del question.config["dreyfus_mapping"]
                reverted += 1

                # Revert Q7 text and labels
                if "How do they approach solving technical problems" in question.question_text:
                    question.question_text = "What is their current skill level in their primary technology domain? (Dreyfus Model)"
                    question.config["labels"] = {
                        "1": "Novice: Follows rules rigidly, needs detailed instructions",
                        "2": "Advanced Beginner: Can handle simple tasks independently",
                        "3": "Competent: Plans deliberately, solves standard problems",
                        "4": "Proficient: Sees the big picture, recognizes patterns",
                        "5": "Expert: Works from intuition, creates new approaches"
                    }

                question.save()

    # Revert Professional Skills questionnaires
    ps_questionnaires = Questionnaire.objects.filter(
        name="Professional Skills 360 Review"
    )

    for questionnaire in ps_questionnaires:
        for question in Question.objects.filter(section__questionnaire=questionnaire):
            if question.config and "dreyfus_mapping" in question.config:
                del question.config["dreyfus_mapping"]
                reverted += 1
                question.save()

    if reverted > 0:
        print(f"Reverted {reverted} questions - removed Dreyfus metadata")


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_add_simple_questionnaire'),
    ]

    operations = [
        migrations.RunPython(
            update_questionnaires_with_dreyfus_metadata,
            reverse_dreyfus_metadata
        ),
    ]
