# Generated by Django 5.2.7 on 2025-11-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_add_dreyfus_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
