# Generated by Django 5.2.17 on 2026-09-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0016_fix_agency_questionnaire_template_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='questionnaires.questionnaire')),
            ],
            options={
                'unique_together': {('questionnaire', 'language')},
            },
        ),
        migrations.CreateModel(
            name='QuestionSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='questionnaires.questionsection')),
            ],
            options={
                'unique_together': {('section', 'language')},
            },
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German')], max_length=10)),
                ('question_text', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='questionnaires.question')),
            ],
            options={
                'unique_together': {('question', 'language')},
            },
        ),
    ]
