# Generated by Django 5.2.7 on 2025-10-23 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_cycles', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_cycles', to='questionnaires.questionnaire')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cycles', to='accounts.reviewee')),
            ],
            options={
                'db_table': 'review_cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('self', 'Self Assessment'), ('peer', 'Peer Review'), ('manager', 'Manager Review'), ('direct_report', 'Direct Report Review')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='reviews.reviewcycle')),
            ],
            options={
                'db_table': 'reviewer_tokens',
                'ordering': ['cycle', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=20)),
                ('answer_data', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaires.question')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reviews.reviewcycle')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reviews.reviewertoken')),
            ],
            options={
                'db_table': 'responses',
                'ordering': ['cycle', 'question'],
                'unique_together': {('token', 'question')},
            },
        ),
    ]
