# Generated by Django 5.2.7 on 2025-10-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewertoken',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewertoken',
            name='reviewer_email',
            field=models.EmailField(blank=True, help_text='Email to send invitation to (not stored with responses for anonymity)', max_length=254, null=True),
        ),
    ]
