# Generated by Django 5.2.7 on 2025-10-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewertoken_invitation_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcycle',
            name='invitation_token_direct_report',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='invitation_token_manager',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='invitation_token_peer',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='invitation_token_self',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
