# Generated by Django 5.2.7 on 2025-10-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewcycle_invitation_token_direct_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewertoken',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When someone claimed this token by clicking the invitation link', null=True),
        ),
    ]
