# Generated by Django 5.2.7 on 2025-11-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_reviewertoken_claimed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewertoken",
            name="last_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last reminder email was sent to this reviewer",
                null=True,
            ),
        ),
    ]
