# Generated by Django 5.2.7 on 2025-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_one_time_login_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_employees',
            field=models.IntegerField(help_text='Maximum total: reviewees + team members combined'),
        ),
    ]
