# Generated by Django 5.2.12 on 2026-10-06 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_upgradestep"),
        ("subscriptions", "0003_alter_plan_max_employees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutFulfilment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("fulfilled", "Fulfilled"),
                            ("rejected_existing_account", "Rejected: email already has an account"),
                            (
                                "rejected_duplicate_subscription",
                                "Rejected: organization already subscribed",
                            ),
                        ],
                        default="fulfilled",
                        max_length=40,
                    ),
                ),
                ("user_created", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_fulfilments",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_fulfilments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "checkout_fulfilments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="onetimelogintoken",
            name="fulfilment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_token",
                to="subscriptions.checkoutfulfilment",
            ),
        ),
        migrations.CreateModel(
            name="RoundPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cycles_remaining", models.PositiveIntegerField(default=10)),
                (
                    "fulfilment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="round_purchase",
                        to="subscriptions.checkoutfulfilment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_purchases",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "round_purchases",
                "ordering": ["created_at"],
            },
        ),
    ]
